package com.elegps.tscweb.model;


import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbAgentInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer Agent_Id;
	private String Agent_Name;
	private String Agent_Address;
	private String Agent_Tel;
	private String Agent_Tel1;
	private String Agent_Email;
	private String Agent_URL;
	private String Agent_Man;
	private String Agent_Man1;
	private String Agent_QQ;
	private Integer Agent_PId;
	private String Agent_Remark;
	private String c01;
	private String c02;
	private String c03;
	private String Agent_Money;//@wanglei ≥‰÷µ”‡∂Ó 
	
	public Integer getAgent_Id() {
		return Agent_Id;
	}
	public void setAgent_Id(Integer agent_Id) {
		Agent_Id = agent_Id;
	}
	public String getAgent_Name() {
		return Agent_Name;
	}
	public void setAgent_Name(String agent_Name) {
		Agent_Name = agent_Name;
	}
	public String getAgent_Address() {
		return Agent_Address;
	}
	public void setAgent_Address(String agent_Address) {
		Agent_Address = agent_Address;
	}
	public String getAgent_Tel() {
		return Agent_Tel;
	}
	public void setAgent_Tel(String agent_Tel) {
		Agent_Tel = agent_Tel;
	}
	public String getAgent_Email() {
		return Agent_Email;
	}
	public void setAgent_Email(String agent_Email) {
		Agent_Email = agent_Email;
	}
	public String getAgent_URL() {
		return Agent_URL;
	}
	public void setAgent_URL(String agent_URL) {
		Agent_URL = agent_URL;
	}
	public String getAgent_Man() {
		return Agent_Man;
	}
	public void setAgent_Man(String agent_Man) {
		Agent_Man = agent_Man;
	}
	public String getAgent_QQ() {
		return Agent_QQ;
	}
	public void setAgent_QQ(String agent_QQ) {
		Agent_QQ = agent_QQ;
	}
	public Integer getAgent_PId() {
		return Agent_PId;
	}
	public void setAgent_PId(Integer agent_PId) {
		Agent_PId = agent_PId;
	}
	public String getAgent_Remark() {
		return Agent_Remark;
	}
	public void setAgent_Remark(String agent_Remark) {
		Agent_Remark = agent_Remark;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
	public String getAgent_Tel1() {
		return Agent_Tel1;
	}
	public void setAgent_Tel1(String agent_Tel1) {
		Agent_Tel1 = agent_Tel1;
	}
	public String getAgent_Man1() {
		return Agent_Man1;
	}
	public void setAgent_Man1(String agent_Man1) {
		Agent_Man1 = agent_Man1;
	}
	/**
	 * @param agent_Money the agent_Money to set
	 */
	public void setAgent_Money(String agent_Money) {
		Agent_Money = agent_Money;
	}
	/**
	 * @return the agent_Money
	 */
	public String getAgent_Money() {
		return Agent_Money;
	}


	// Constructors

	/** default constructor */

	
	

}