package com.elegps.tscweb.model;


import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbEnterpriseInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer Ep_Id;
	private String Ep_Name;
	private String Ep_Address;
	private String Ep_Tel;
	private String Ep_Tel1;
	private String Ep_Email;
	private String Ep_URL;
	private String Ep_Man;
	private String Ep_Man1;
	private String Ep_QQ;
	private Integer Agent_Id;
	private String Ep_Remark;
	private String c01;
	private String c02;
	private String c03;
	private String Ep_Money;//@wanglei ≥‰÷µ”‡∂Ó 

	public Integer getEp_Id() {
		return Ep_Id;
	}
	public void setEp_Id(Integer ep_Id) {
		Ep_Id = ep_Id;
	}
	public String getEp_Name() {
		return Ep_Name;
	}
	public void setEp_Name(String ep_Name) {
		Ep_Name = ep_Name;
	}
	public String getEp_Address() {
		return Ep_Address;
	}
	public void setEp_Address(String ep_Address) {
		Ep_Address = ep_Address;
	}
	public String getEp_Tel() {
		return Ep_Tel;
	}
	public void setEp_Tel(String ep_Tel) {
		Ep_Tel = ep_Tel;
	}
	public String getEp_Email() {
		return Ep_Email;
	}
	public void setEp_Email(String ep_Email) {
		Ep_Email = ep_Email;
	}
	public String getEp_URL() {
		return Ep_URL;
	}
	public void setEp_URL(String ep_URL) {
		Ep_URL = ep_URL;
	}
	public String getEp_Man() {
		return Ep_Man;
	}
	public void setEp_Man(String ep_Man) {
		Ep_Man = ep_Man;
	}
	public String getEp_QQ() {
		return Ep_QQ;
	}
	public void setEp_QQ(String ep_QQ) {
		Ep_QQ = ep_QQ;
	}
	public int getAgent_Id() {
		return Agent_Id;
	}
	public void setAgent_Id(int agent_Id) {
		Agent_Id = agent_Id;
	}
	public String getEp_Remark() {
		return Ep_Remark;
	}
	public void setEp_Remark(String ep_Remark) {
		Ep_Remark = ep_Remark;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
	public String getEp_Tel1() {
		return Ep_Tel1;
	}
	public void setEp_Tel1(String ep_Tel1) {
		Ep_Tel1 = ep_Tel1;
	}
	public String getEp_Man1() {
		return Ep_Man1;
	}
	public void setEp_Man1(String ep_Man1) {
		Ep_Man1 = ep_Man1;
	}
	/**
	 * @param ep_Money the ep_Money to set
	 */
	public void setEp_Money(String ep_Money) {
		Ep_Money = ep_Money;
	}
	/**
	 * @return the ep_Money
	 */
	public String getEp_Money() {
		return Ep_Money;
	}
	
	
	

}