package com.elegps.tscweb.model;


import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbEpChargeInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer deductid;
	private Integer orgId;
	private Integer orgType;
	private Integer epId;
	private Date deductDate;
	private Integer deductCash;
	private String c01;
	private String c02;
	private String c03;
	
	public Integer getDeductid() {
		return deductid;
	}
	public void setDeductid(Integer deductid) {
		this.deductid = deductid;
	}
	public Integer getOrgId() {
		return orgId;
	}
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}
	public Integer getOrgType() {
		return orgType;
	}
	public void setOrgType(Integer orgType) {
		this.orgType = orgType;
	}
	public Integer getEpId() {
		return epId;
	}
	public void setEpId(Integer epId) {
		this.epId = epId;
	}
	public Date getDeductDate() {
		return deductDate;
	}
	public void setDeductDate(Date deductDate) {
		this.deductDate = deductDate;
	}
	public Integer getDeductCash() {
		return deductCash;
	}
	public void setDeductCash(Integer deductCash) {
		this.deductCash = deductCash;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
	
	
	

}