package com.elegps.tscweb.model;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbGpsMsListInfo implements Serializable {

	private static final long serialVersionUID = 1L;
	private String gpsop_id;
	private String l_ms_id;
	private String ms_id;
	private Date create_time;
	
	
	 // 必须重新定义equals()与hashCode()

	  public boolean equals(Object obj) {

	      if(obj == this) {

	          return true;

	      }
	      if(!(obj instanceof TbGpsMsListInfo)) {

	          return false;

	      }

	      TbGpsMsListInfo psmslist = (TbGpsMsListInfo) obj;
	      return new EqualsBuilder()
	               .append(this.gpsop_id, psmslist.getGpsop_id())
	               .append(this.l_ms_id, psmslist.getL_ms_id())
	               .isEquals();
	  }

	 

	  public int hashCode() {

	      return new HashCodeBuilder()

	               .append(this.gpsop_id)

	               .append(this.l_ms_id)

	               .toHashCode();

	  }
	public String getGpsop_id() {
		return gpsop_id;
	}
	public void setGpsop_id(String gpsop_id) {
		this.gpsop_id = gpsop_id;
	}
	public String getL_ms_id() {
		return l_ms_id;
	}
	public void setL_ms_id(String l_ms_id) {
		this.l_ms_id = l_ms_id;
	}
	public String getMs_id() {
		return ms_id;
	}
	public void setMs_id(String ms_id) {
		this.ms_id = ms_id;
	}



	public Date getCreate_time() {
		return create_time;
	}



	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	

}