package com.elegps.tscweb.model;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbGrpMsListInfo implements Serializable {
  private String ms_id;
  private String grp_id;
  private int is_creator;
  private int config;
  private Date create_time;
  private String c01;
  private String c02;
  private String c03;
  private String c04;
  
  
  // 必须重新定义equals()与hashCode()

  public boolean equals(Object obj) {

      if(obj == this) {

          return true;

      }
      if(!(obj instanceof TbGrpMsListInfo)) {

          return false;

      }

      TbGrpMsListInfo grpmslist = (TbGrpMsListInfo) obj;
      return new EqualsBuilder()
               .append(this.ms_id, grpmslist.getMs_id())

               .append(this.grp_id, grpmslist.getGrp_id())

               .isEquals();
  }

 

  public int hashCode() {

      return new HashCodeBuilder()

               .append(this.ms_id)

               .append(this.grp_id)

               .toHashCode();

  }



public String getMs_id() {
	return ms_id;
}



public void setMs_id(String ms_id) {
	this.ms_id = ms_id;
}



public String getGrp_id() {
	return grp_id;
}



public void setGrp_id(String grp_id) {
	this.grp_id = grp_id;
}



public int getIs_creator() {
	return is_creator;
}



public void setIs_creator(int is_creator) {
	this.is_creator = is_creator;
}



public int getConfig() {
	return config;
}



public void setConfig(int config) {
	this.config = config;
}



public String getC01() {
	return c01;
}



public void setC01(String c01) {
	this.c01 = c01;
}



public String getC02() {
	return c02;
}



public void setC02(String c02) {
	this.c02 = c02;
}



public String getC03() {
	return c03;
}



public void setC03(String c03) {
	this.c03 = c03;
}



public String getC04() {
	return c04;
}



public void setC04(String c04) {
	this.c04 = c04;
}



public Date getCreate_time() {
	return create_time;
}



public void setCreate_time(Date create_time) {
	this.create_time = create_time;
}


}