package com.elegps.tscweb.model;

import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbGrpInfo implements java.io.Serializable {

	// Fields
	private String grpid;
	private String grpname;
	private String msid;
	private Date regtime;
	private Integer status;
	private String pptmsid; 
	private Integer grptype;
	private Integer flag;
	private Long pttstart;
	private Long talkinglast;
	private Integer Ep_Id;
	private Integer grplf;
	private String grppid;
	private String c03;
	private String c04;
	private String c05;
	private String c06;
	private String c07;
	private String c08;
	private String c09;
	private String c10;
	
	private String serverIp;//ËùÊô·þÎñÆ÷IP


	// Constructors

	/** default constructor */
	public TbGrpInfo() {
	}

	/** minimal constructor */
	public TbGrpInfo(String grpid, String grpname,String msid,Date regtime,Integer status,String pptmsid,Integer grptype,
			Integer flag,Integer pttstart,Integer talkinglast) {
		this.grpid = grpid;
		this.grpname = grpname;
		this.msid = msid;
		this.regtime = regtime;
		this.status = status;
		this.pptmsid = pptmsid;
		this.grptype = grptype;
		this.flag = flag;
//		this.pttstart=pttstart;
//		this.talkinglast=talkinglast;
	}

	/** full constructor */
	public TbGrpInfo(String grpid, String grpname,String msid,Date regtime,Integer status,String pptmsid,Integer grptype,
			Integer flag,Long pttstart,Long talkinglast,String c03,String c04,String c05,String c06,String c07,
			String c08,String c09,String c10) {
	
		this.grpid = grpid;
		this.grpname = grpname;
		this.msid = msid;
		this.regtime = regtime;
		this.status = status;
		this.pptmsid = pptmsid;
		this.grptype = grptype;
		this.flag = flag;
		this.pttstart=pttstart;
		this.talkinglast=talkinglast;
		this.c03=c03;
		this.c04=c04;
		this.c05=c05;
		this.c06=c06;
		this.c07=c07;
		this.c08=c08;
		this.c09=c09;
		this.c10=c10;
	}
	// Property accessors

	public String getGrpid() {
		return grpid;
	}

	public void setGrpid(String grpid) {
		this.grpid = grpid;
	}

	public String getGrpname() {
		return grpname;
	}

	public void setGrpname(String grpname) {
		this.grpname = grpname;
	}

	public String getMsid() {
		return msid;
	}

	public void setMsid(String msid) {
		this.msid = msid;
	}

	public Date getRegtime() {
		return regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getPptmsid() {
		return pptmsid;
	}

	public void setPptmsid(String pptmsid) {
		this.pptmsid = pptmsid;
	}

	public Integer getGrptype() {
		return grptype;
	}

	public void setGrptype(Integer grptype) {
		this.grptype = grptype;
	}

	public Integer getFlag() {
		return flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public Long getPttstart() {
		return pttstart;
	}

	public void setPttstart(Long pttstart) {
		this.pttstart = pttstart;
	}

	public Long getTalkinglast() {
		return talkinglast;
	}

	public void setTalkinglast(Long talkinglast) {
		this.talkinglast = talkinglast;
	}

	public String getC03() {
		return c03;
	}

	public void setC03(String c03) {
		this.c03 = c03;
	}

	public String getC04() {
		return c04;
	}

	public void setC04(String c04) {
		this.c04 = c04;
	}

	public String getC05() {
		return c05;
	}

	public void setC05(String c05) {
		this.c05 = c05;
	}

	public String getC06() {
		return c06;
	}

	public void setC06(String c06) {
		this.c06 = c06;
	}

	public String getC07() {
		return c07;
	}

	public void setC07(String c07) {
		this.c07 = c07;
	}

	public String getC08() {
		return c08;
	}

	public void setC08(String c08) {
		this.c08 = c08;
	}

	public String getC09() {
		return c09;
	}

	public void setC09(String c09) {
		this.c09 = c09;
	}

	public String getC10() {
		return c10;
	}

	public void setC10(String c10) {
		this.c10 = c10;
	}

	public Integer getEp_Id() {
		return Ep_Id;
	}

	public void setEp_Id(Integer ep_Id) {
		Ep_Id = ep_Id;
	}

	public Integer getGrplf() {
		return grplf;
	}

	public void setGrplf(Integer grplf) {
		this.grplf = grplf;
	}

	public String getGrppid() {
		return grppid;
	}

	public void setGrppid(String grppid) {
		this.grppid = grppid;
	}

	/**
	 * @param serverIp the serverIp to set
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	/**
	 * @return the serverIp
	 */
	public String getServerIp() {
		return serverIp;
	}

}