package com.elegps.tscweb.model;

import java.util.Date;

/**
 * TbKoFeiLogInfo generated by MyEclipse Persistence Tools
 */

public class TbKoFeiLogInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer id;		
	private String msid;	//扣费终端号
	private Date time; //扣费时间
	private Integer type;	//0,文字。1.语音。2.图片
	private Integer msgId; //对应信息id
	private Double money; //扣费金额
	private Integer grpOrNot;	//0:单对单聊天。1：群组聊天
	private String imsi; //船家宝ID
	
	public TbKoFeiLogInfo(){
		
	}
	
	public TbKoFeiLogInfo(Integer id,String msid,Date time,Integer type,Integer msgId,Double money,Integer grpOrNot){
		this.id = id;
		this.msid = msid;
		this.grpOrNot= grpOrNot;
		this.time = time;
		this.type = type;
		this.msgId = msgId;
		this.money =money;
	}

	public Integer getId() {
		return id;
	}

	public String getMsid() {
		return msid;
	}

	public Date getTime() {
		return time;
	}

	public Integer getType() {
		return type;
	}

	public Integer getMsgId() {
		return msgId;
	}

	public Double getMoney() {
		return money;
	}

	public Integer getGrpOrNot() {
		return grpOrNot;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setMsid(String msid) {
		this.msid = msid;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public void setGrpOrNot(Integer grpOrNot) {
		this.grpOrNot = grpOrNot;
	}

	public String getImsi() {
		return imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}
}