package com.elegps.tscweb.model;


import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbMsChargeInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer chargeid;
	private String msId;
	private Integer chargeCash;
	private Date chargeDate;
	private Integer epId;
	private String c01;
	private String c02;
	private String c03;
	public Integer getChargeid() {
		return chargeid;
	}
	public void setChargeid(Integer chargeid) {
		this.chargeid = chargeid;
	}
	public String getMsId() {
		return msId;
	}
	public void setMsId(String msId) {
		this.msId = msId;
	}
	public Integer getChargeCash() {
		return chargeCash;
	}
	public void setChargeCash(Integer chargeCash) {
		this.chargeCash = chargeCash;
	}
	public Date getChargeDate() {
		return chargeDate;
	}
	public void setChargeDate(Date chargeDate) {
		this.chargeDate = chargeDate;
	}
	public Integer getEpId() {
		return epId;
	}
	public void setEpId(Integer epId) {
		this.epId = epId;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
}