package com.elegps.tscweb.model;

import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbMsInfo implements java.io.Serializable {

	// Fields

	private String msId;
	private String msName;
	private String passwd;
	private Integer msType;
	private Integer onlineStatus;
	private Integer callSize;
	private Integer listenSize;
	private Integer callTime;
	private Integer listenTime;
	private String grpCalling;
	private Date lastCalling;
	private Integer flag;
	private Date create_time;
	private Date LastPostGps_time;
	private String mobileid;
	private Integer epid;
	private Integer msLevel;
	private Integer is_Arrearage;
	private Integer msMessage_post;
	private Integer balance_cash;
	private String charge_date;
	private Integer package_fee;
	private Integer msdf;
	private Integer mscall;
	private Integer mileageas;
	//wanglei
	private Date msMoneyTime;//套餐到期时间
	private TbPFInfo pf;//套餐类型
	private String netWorkType; //网络类型（c:电信、W：联通、M：移动）
	private String msCategory;//终端类型（A18.....）
	
	private Integer agentId;//代理商ID
	
	private String phoneLogin;//手机号登录绑定
	private String msMoney;//终端余额（船家宝APP使用）
	/**
	 * @return the msMoney
	 */
	public String getMsMoney() {
		return msMoney;
	}


	/**
	 * @param msMoney the msMoney to set
	 */
	public void setMsMoney(String msMoney) {
		this.msMoney = msMoney;
	}


	/**
	 *  2011-03-26 已使用
	 *  c01
	 */
	private String c01;
	private String c02;
	/**
	 * 2011-11-09 
	 * 终端转换成打电话：0：禁止转换;1：允许转换
	 */
	private String c03;
	/**
	 * 2011-11-09
	 * 终端是车机或者手持机：0：车机;1：手持机
	 */
	private String c04;
	/**
	 * @date 2011-11-24
	 * 终端型号：
	 * 1:博科PTT终端    --BK_PTT
	 * 2:博科定位终端   --BK_GPS
	 * 4：大三通        --BK_803
	 * 8：国标(T808)    --T808
	 * 16：海尔HR3000   --HR3000
	 * 32：BK_K6        --BK_K6
	 */
	private String c05;
	private String c06;
	/**
	 * 终端别名拼音(前5位)
	 */
	private String c07;
	private String c08;
	/**
	 * 通话类型：0：禁止通话（不能听和呼）;1：只听;2：只呼调度;4：正常通话(默认)
	 */
	private int c09;
	private String c10;
	private String c11;
	private String c12;

	/**
	 * 船家宝App角色：（0：船长，1：船员）
	 */
	private Integer roleType;

	/**
	 * 船家宝App用户的亲情号码，逗号拼接
	 */
	private String familyNumbers;


	// Constructors

	/** default constructor */
	public TbMsInfo() {
	}


	// Property accessors

	public String getMsId() {
		return this.msId;
	}

	public void setMsId(String msId) {
		this.msId = msId;
	}

	public String getMsName() {
		return this.msName;
	}

	public void setMsName(String msName) {
		this.msName = msName;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Integer getMsType() {
		return this.msType;
	}

	public void setMsType(Integer msType) {
		this.msType = msType;
	}

	public Integer getOnlineStatus() {
		return this.onlineStatus;
	}

	public void setOnlineStatus(Integer onlineStatus) {
		this.onlineStatus = onlineStatus;
	}

	public Integer getCallSize() {
		return this.callSize;
	}

	public void setCallSize(Integer callSize) {
		this.callSize = callSize;
	}

	public Integer getListenSize() {
		return this.listenSize;
	}

	public void setListenSize(Integer listenSize) {
		this.listenSize = listenSize;
	}

	public Integer getCallTime() {
		return this.callTime;
	}

	public void setCallTime(Integer callTime) {
		this.callTime = callTime;
	}

	public Integer getListenTime() {
		return this.listenTime;
	}

	public void setListenTime(Integer listenTime) {
		this.listenTime = listenTime;
	}

	public String getGrpCalling() {
		return this.grpCalling;
	}

	public void setGrpCalling(String grpCalling) {
		this.grpCalling = grpCalling;
	}

	public Date getLastCalling() {
		return this.lastCalling;
	}

	public void setLastCalling(Date lastCalling) {
		this.lastCalling = lastCalling;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public String getC01() {
		return this.c01;
	}

	public void setC01(String c01) {
		this.c01 = c01;
	}

	public String getC02() {
		return this.c02;
	}

	public void setC02(String c02) {
		this.c02 = c02;
	}

	public String getC03() {
		return this.c03;
	}

	public void setC03(String c03) {
		this.c03 = c03;
	}

	public String getC04() {
		return this.c04;
	}

	public void setC04(String c04) {
		this.c04 = c04;
	}

	public String getC05() {
		return this.c05;
	}

	public void setC05(String c05) {
		this.c05 = c05;
	}

	public String getC06() {
		return this.c06;
	}

	public void setC06(String c06) {
		this.c06 = c06;
	}

	public String getC07() {
		return this.c07;
	}

	public void setC07(String c07) {
		this.c07 = c07;
	}

	public String getC08() {
		return this.c08;
	}

	public void setC08(String c08) {
		this.c08 = c08;
	}

	public int getC09() {
		return this.c09;
	}

	public void setC09(int c09) {
		this.c09 = c09;
	}

	public String getC10() {
		return this.c10;
	}

	public void setC10(String c10) {
		this.c10 = c10;
	}

	public String getC11() {
		return this.c11;
	}

	public void setC11(String c11) {
		this.c11 = c11;
	}

	public String getC12() {
		return this.c12;
	}

	public void setC12(String c12) {
		this.c12 = c12;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getLastPostGps_time() {
		return LastPostGps_time;
	}

	public void setLastPostGps_time(Date lastPostGps_time) {
		LastPostGps_time = lastPostGps_time;
	}

	public Integer getEpid() {
		return epid;
	}

	public void setEpid(Integer epid) {
		this.epid = epid;
	}

	public String getMobileid() {
		return mobileid;
	}

	public void setMobileid(String mobileid) {
		this.mobileid = mobileid;
	}

	public Integer getMsLevel() {
		return msLevel;
	}

	public void setMsLevel(Integer msLevel) {
		this.msLevel = msLevel;
	}

	public Integer getIs_Arrearage() {
		return is_Arrearage;
	}

	public void setIs_Arrearage(Integer is_Arrearage) {
		this.is_Arrearage = is_Arrearage;
	}

	public Integer getMsMessage_post() {
		return msMessage_post;
	}

	public void setMsMessage_post(Integer msMessage_post) {
		this.msMessage_post = msMessage_post;
	}

	public Integer getBalance_cash() {
		return balance_cash;
	}

	public void setBalance_cash(Integer balance_cash) {
		this.balance_cash = balance_cash;
	}


	public String getCharge_date() {
		return charge_date;
	}

	public void setCharge_date(String charge_date) {
		this.charge_date = charge_date;
	}

	public int getPackage_fee() {
		return package_fee;
	}

	public void setPackage_fee(Integer package_fee) {
		this.package_fee = package_fee;
	}

	public int getMsdf() {
		return msdf;
	}

	public void setMsdf(Integer msdf) {
		this.msdf = msdf;
	}

	public Integer getMscall() {
		return mscall;
	}

	public void setMscall(Integer mscall) {
		this.mscall = mscall;
	}


	public Integer getMileageas() {
		return mileageas;
	}


	public void setMileageas(Integer mileageas) {
		this.mileageas = mileageas;
	}


	/**
	 * @param msMoneyTime the msMoneyTime to set
	 */
	public void setMsMoneyTime(Date msMoneyTime) {
		this.msMoneyTime = msMoneyTime;
	}


	/**
	 * @return the msMoneyTime
	 */
	public Date getMsMoneyTime() {
		return msMoneyTime;
	}


	/**
	 * @param pf the pf to set
	 */
	public void setPf(TbPFInfo pf) {
		this.pf = pf;
	}


	/**
	 * @return the pf
	 */
	public TbPFInfo getPf() {
		return pf;
	}


	/**
	 * @param netWorkType the netWorkType to set
	 */
	public void setNetWorkType(String netWorkType) {
		this.netWorkType = netWorkType;
	}


	/**
	 * @return the netWorkType
	 */
	public String getNetWorkType() {
		return netWorkType;
	}


	/**
	 * @param msCategory the msCategory to set
	 */
	public void setMsCategory(String msCategory) {
		this.msCategory = msCategory;
	}


	/**
	 * @return the msCategory
	 */
	public String getMsCategory() {
		return msCategory;
	}


	/**
	 * @param angentId the angentId to set
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}


	/**
	 * @return the angentId
	 */
	public Integer getAgentId() {
		return agentId;
	}


	/**
	 * @param phoneLogin the phoneLogin to set
	 */
	public void setPhoneLogin(String phoneLogin) {
		this.phoneLogin = phoneLogin;
	}


	/**
	 * @return the phoneLogin
	 */
	public String getPhoneLogin() {
		return phoneLogin;
	}

	public Integer getRoleType() {
		return roleType;
	}

	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	public String getFamilyNumbers() {
		return familyNumbers;
	}

	public void setFamilyNumbers(String familyNumbers) {
		this.familyNumbers = familyNumbers;
	}
}