package com.elegps.tscweb.model;


import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbMSDeductInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer deductid;
	private String msId;
	private Integer epId;
	private Integer deductcash;
	private Date deductdate;
	private String c01;
	private String c02;
	private String c03;
	public Integer getDeductid() {
		return deductid;
	}
	public void setDeductid(Integer deductid) {
		this.deductid = deductid;
	}
	public String getMsId() {
		return msId;
	}
	public void setMsId(String msId) {
		this.msId = msId;
	}
	public Integer getEpId() {
		return epId;
	}
	public void setEpId(Integer epId) {
		this.epId = epId;
	}
	public Integer getDeductcash() {
		return deductcash;
	}
	public void setDeductcash(Integer deductcash) {
		this.deductcash = deductcash;
	}
	public Date getDeductdate() {
		return deductdate;
	}
	public void setDeductdate(Date deductdate) {
		this.deductdate = deductdate;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
	
}