package com.elegps.tscweb.model;

import java.util.Date;

/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbORGAdvanceInfo implements java.io.Serializable {

	// Fields
	private Integer advanceId;
	private Integer orgType;
	private Integer orgId;
	private Integer advanceCash;
	private Date advanceDate;
	private String advancePerson;
	private Date validateDate;
	private String validatePerson;
	private Integer validateResult;
	private String remark;
	private String c01;
	private String c02;
	private String c03;
	public Integer getAdvanceId() {
		return advanceId;
	}
	public void setAdvanceId(Integer advanceId) {
		this.advanceId = advanceId;
	}

	public Integer getAdvanceCash() {
		return advanceCash;
	}
	public void setAdvanceCash(Integer advanceCash) {
		this.advanceCash = advanceCash;
	}
	public Date getAdvanceDate() {
		return advanceDate;
	}
	public void setAdvanceDate(Date advanceDate) {
		this.advanceDate = advanceDate;
	}
	public String getAdvancePerson() {
		return advancePerson;
	}
	public void setAdvancePerson(String advancePerson) {
		this.advancePerson = advancePerson;
	}
	public Date getValidateDate() {
		return validateDate;
	}
	public void setValidateDate(Date validateDate) {
		this.validateDate = validateDate;
	}
	public String getValidatePerson() {
		return validatePerson;
	}
	public void setValidatePerson(String validatePerson) {
		this.validatePerson = validatePerson;
	}
	public Integer getValidateResult() {
		return validateResult;
	}
	public void setValidateResult(Integer validateResult) {
		this.validateResult = validateResult;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getC01() {
		return c01;
	}
	public void setC01(String c01) {
		this.c01 = c01;
	}
	public String getC02() {
		return c02;
	}
	public void setC02(String c02) {
		this.c02 = c02;
	}
	public String getC03() {
		return c03;
	}
	public void setC03(String c03) {
		this.c03 = c03;
	}
	public Integer getOrgType() {
		return orgType;
	}
	public void setOrgType(Integer orgType) {
		this.orgType = orgType;
	}
	public Integer getOrgId() {
		return orgId;
	}
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}
	

	
}