package com.elegps.tscweb.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * TbMsInfo generated by MyEclipse Persistence Tools
 */

public class TbORGBalanceInfo implements Serializable {
  private Integer orgId;
  private Integer orgType;
  private Integer balanceCash;
  private String c01;
  private String c02;
  private String c03;

  
  
  // 必须重新定义equals()与hashCode()

  public boolean equals(Object obj) {

      if(obj == this) {

          return true;

      }
      if(!(obj instanceof TbGrpMsListInfo)) {

          return false;

      }

      TbORGBalanceInfo ORGBalance = (TbORGBalanceInfo) obj;
      return new EqualsBuilder()
               .append(this.orgId, ORGBalance.getOrgId())

               .append(this.orgType, ORGBalance.getOrgType())

               .isEquals();
  }

 

  public int hashCode() {

      return new HashCodeBuilder()

               .append(this.orgId)

               .append(this.orgType)

               .toHashCode();

  }









public Integer getBalanceCash() {
	return balanceCash;
}



public void setBalanceCash(Integer balanceCash) {
	this.balanceCash = balanceCash;
}



public String getC01() {
	return c01;
}



public void setC01(String c01) {
	this.c01 = c01;
}



public String getC02() {
	return c02;
}



public void setC02(String c02) {
	this.c02 = c02;
}



public String getC03() {
	return c03;
}



public void setC03(String c03) {
	this.c03 = c03;
}



public Integer getOrgId() {
	return orgId;
}



public void setOrgId(Integer orgId) {
	this.orgId = orgId;
}



public Integer getOrgType() {
	return orgType;
}



public void setOrgType(Integer orgType) {
	this.orgType = orgType;
}





}