/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.elegps.tscweb.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 3-6-2009
 * 
 * XDoclet definition:
 * @struts.form name="AddEpForm"
 */
public class AddEpForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String ep_id;
	private String ep_name;
	private String ep_address;
	private String ep_tel;
	private String ep_tel1;
	private String ep_email;
	private String ep_url;
	private String ep_man;
	private String ep_man1;
	private String ep_qq;
	private String pagentid;
	private String childagentid;
	private String ep_remark;


	/*
	 * Generated Methods
	 */

	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getEp_name() {
		return ep_name;
	}

	public void setEp_name(String ep_name) {
		this.ep_name = ep_name;
	}

	public String getEp_address() {
		return ep_address;
	}

	public void setEp_address(String ep_address) {
		this.ep_address = ep_address;
	}

	public String getEp_tel() {
		return ep_tel;
	}

	public void setEp_tel(String ep_tel) {
		this.ep_tel = ep_tel;
	}

	public String getEp_email() {
		return ep_email;
	}

	public void setEp_email(String ep_email) {
		this.ep_email = ep_email;
	}

	public String getEp_url() {
		return ep_url;
	}

	public void setEp_url(String ep_url) {
		this.ep_url = ep_url;
	}

	public String getEp_man() {
		return ep_man;
	}

	public void setEp_man(String ep_man) {
		this.ep_man = ep_man;
	}

	public String getEp_qq() {
		return ep_qq;
	}

	public void setEp_qq(String ep_qq) {
		this.ep_qq = ep_qq;
	}



	public String getPagentid() {
		return pagentid;
	}

	public void setPagentid(String pagentid) {
		this.pagentid = pagentid;
	}

	public String getChildagentid() {
		return childagentid;
	}

	public void setChildagentid(String childagentid) {
		this.childagentid = childagentid;
	}

	public String getEp_remark() {
		return ep_remark;
	}

	public void setEp_remark(String ep_remark) {
		this.ep_remark = ep_remark;
	}

	public String getEp_id() {
		return ep_id;
	}

	public void setEp_id(String ep_id) {
		this.ep_id = ep_id;
	}

	public String getEp_tel1() {
		return ep_tel1;
	}

	public void setEp_tel1(String ep_tel1) {
		this.ep_tel1 = ep_tel1;
	}

	public String getEp_man1() {
		return ep_man1;
	}

	public void setEp_man1(String ep_man1) {
		this.ep_man1 = ep_man1;
	}

	}