/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.elegps.tscweb.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="addmsform"
 */
public class AddgrpForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** password property */
	private String grp_id;

	/** ms_type property */
	private String grp_name;

	/** ms_id property */
	private String ms_id;

	/** ms_name property */
	private String grp_type;
	
	private String talkinglast;
	private String ep;
	private String grp_lf;

	/*
	 * Generated Methods
	 */

	

	public String getGrp_lf() {
		return grp_lf;
	}

	public void setGrp_lf(String grp_lf) {
		this.grp_lf = grp_lf;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getGrp_id() {
		return grp_id;
	}

	public void setGrp_id(String grp_id) {
		this.grp_id = grp_id;
	}

	public String getGrp_name() {
		return grp_name;
	}

	public void setGrp_name(String grp_name) {
		this.grp_name = grp_name;
	}

	public String getMs_id() {
		return ms_id;
	}

	public void setMs_id(String ms_id) {
		this.ms_id = ms_id;
	}

	public String getGrp_type() {
		return grp_type;
	}

	public void setGrp_type(String grp_type) {
		this.grp_type = grp_type;
	}

	public String getTalkinglast() {
		return talkinglast;
	}

	public void setTalkinglast(String talkinglast) {
		this.talkinglast = talkinglast;
	}

	public String getEp() {
		return ep;
	}

	public void setEp(String ep) {
		this.ep = ep;
	}

	
	
}