/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.elegps.tscweb.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="addmsform"
 */
public class AddmsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** password property */
	private String password;
	
	private String mssl;

	/** ms_type property */
	private String ms_type;

	/** ms_id property */
	private String ms_id;

	/** ms_name property */
	private String ms_name;
	 
	private String ms_flag;
	
	private String memo;
	
	private String ep;
	
	private String ms_modid;
	
	private String ms_level;
	
	private int package_fee;
	 
	private int ms_df;
	
	private int call;
	
	private int mileageas;
	private String c03;
	private String c04;
	private String c05;
	private String nwType;//网络类型
	private String pfType;//套餐类型
	/*
	 * Generated Methods
	 */

	public int getMileageas() {
		return mileageas;
	}

	public void setMileageas(int mileageas) {
		this.mileageas = mileageas;
	}

	public int getCall() {
		return call;
	}

	public void setCall(int call) {
		this.call = call;
	}

	public int getMs_df() {
		return ms_df;
	}

	public void setMs_df(int ms_df) {
		this.ms_df = ms_df;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the ms_type.
	 * @return String
	 */
	public String getMs_type() {
		return ms_type;
	}

	/** 
	 * Set the ms_type.
	 * @param ms_type The ms_type to set
	 */
	public void setMs_type(String ms_type) {
		this.ms_type = ms_type;
	}

	/** 
	 * Returns the ms_id.
	 * @return String
	 */
	public String getMs_id() {
		return ms_id;
	}

	/** 
	 * Set the ms_id.
	 * @param ms_id The ms_id to set
	 */
	public void setMs_id(String ms_id) {
		this.ms_id = ms_id;
	}

	/** 
	 * Returns the ms_name.
	 * @return String
	 */
	public String getMs_name() {
		return ms_name;
	}

	/** 
	 * Set the ms_name.
	 * @param ms_name The ms_name to set
	 */
	public void setMs_name(String ms_name) {
		this.ms_name = ms_name;
	}

	public String getMs_flag() {
		return ms_flag;
	}

	public void setMs_flag(String ms_flag) {
		this.ms_flag = ms_flag;
	}

	public String getMssl() {
		return mssl;
	}

	public void setMssl(String mssl) {
		this.mssl = mssl;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getMs_modid() {
		return ms_modid;
	}

	public void setMs_modid(String ms_modid) {
		this.ms_modid = ms_modid;
	}

	public String getMs_level() {
		return ms_level;
	}

	public void setMs_level(String ms_level) {
		this.ms_level = ms_level;
	}

	public int getPackage_fee() {
		return package_fee;
	}

	public void setPackage_fee(int package_fee) {
		this.package_fee = package_fee;
	}

	public String getEp() {
		return ep;
	}

	public void setEp(String ep) {
		this.ep = ep;
	}

	public String getC03() {
		return c03;
	}

	public void setC03(String c03) {
		this.c03 = c03;
	}

	public String getC04() {
		return c04;
	}

	public void setC04(String c04) {
		this.c04 = c04;
	}

	public String getC05() {
		return c05;
	}

	public void setC05(String c05) {
		this.c05 = c05;
	}

	/**
	 * @param nwType the nwType to set
	 */
	public void setNwType(String nwType) {
		this.nwType = nwType;
	}

	/**
	 * @return the nwType
	 */
	public String getNwType() {
		return nwType;
	}

	/**
	 * @param pfType the pfType to set
	 */
	public void setPfType(String pfType) {
		this.pfType = pfType;
	}

	/**
	 * @return the pfType
	 */
	public String getPfType() {
		return pfType;
	}


}